config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
# frozen_string_literal: true
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = correct_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    redirect_to friends_path
  end

  def correct_user
    @firend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not Authorized to Edit' if @friend.nil
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def about
    @about_me = 'My name is Ben Saulnier'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %> <% if friend.errors.any?
%>
<div id="error_explanation">
  <h2>
    <%= pluralize(friend.errors.count, "error") %> prohibited this friend from
    being saved:
  </h2>

  <ul>
    <% friend.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">
  <% form.label :first_name %> <%= form.text_field :first_name,
  class:"form-control", placeholder: "First Name" %>
</div>
<br />
<div class="field form-group">
  <% form.label :last_name %> <%= form.text_field :last_name,
  class:"form-control", placeholder: "Last Name" %>
</div>
<br />
<div class="field form-group">
  <% form.label :email %> <%= form.text_field :email, class:"form-control",
  placeholder: "Email" %>
</div>
<br />
<div class="field form-group">
  <% form.label :phone %> <%= form.text_field :phone, class:"form-control",
  placeholder: "Phone Number" %>
</div>
<br />
<div class="field form-group">
  <% form.label :twitter %> <%= form.text_field :twitter, class:"form-control",
  placeholder: "Twitter" %>
</div>
<br />
<div class="field form-group">
  <%= form.number_field :user_id, id: :friend_user_id, class:"form-control",
  value: current_user.id, type: :hidden %>
</div>
<br/>
<div class="actions"><%= form.submit class:'btn btn-secondary' %></div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User Id </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= button_to 'Destroy', friend, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')", class:"btn btn-danger" %></td>
        </tr>
        <% end %>
        <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>
<h1>test</h1>
<% end %> 
 

app/views/friends/new.html.erb
<h1>New Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Back', friends_path, class:'btn btn-secondary' %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friend.twitter %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> |
<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/home/_header.html.erb
<nav class="navbar-expand-lg navbar-nav navbar-dark bg-dark">
  <div class="row">
    <div class="col-sm-1 left">
      <%= link_to 'Amazon' , root_path, class:"navbar-brand" %>
    </div>
    <% if user_signed_in? %>
      <div class="col-sm-1">
        <%= link_to "Sign Out" , destroy_user_session_path, method: :delete, class:"nav-link" %>
      </div>
      <div class="col-sm-1">
        <%= link_to "Edit Profile" , edit_user_registration_path, class:"nav-link" %>
      </div>
      <% else %>
        <div class="col-sm-1">
          <%= link_to "Sign In" , new_user_session_path, class:"nav-link" %>
        </div>
        <div class="col-sm-1">
          <%= link_to 'Sign Up' , new_user_registration_path, class:"nav-link" %>
        </div>

        <% end %>

          <div class="col">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" </form>
            </form>
          </div>
          <div class="col-sm-3">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </div>
  </div>



</nav>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>About us....</h1>
      <%= @about_me %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<main>
  <section class="py-5 text-center container">
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

 